# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

@contact=Contact.create!(:name => "All")

@client=ContactType.create!(:name => 'Client')
ContactType.create!(:name => 'Broker')
ContactType.create!(:name => 'Vendor')
ContactType.create!(:name => 'Employee')
ContactType.create!(:name => 'Friend')

User.create!(:name => "Administrator", :email => 'admin@tss.com', :password => 'secret', :password_confirmation => 'secret', :admin => true)

MovingRequirement.create!(:name => "Landlord NOC")
MovingRequirement.create!(:name => "Police Notification")
MovingRequirement.create!(:name => "Clubhouse Formalities")

Quality.create!(:name => "Great", :value => "3")
Quality.create!(:name => "Regular", :value => "2")
Quality.create!(:name => "Budget", :value => "1")

City.create!(:name => "Mumbai")

Area.create!(:city_id=>'1',:name=>'Colaba',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Churchgate',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Fort',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Breach Candy',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Dadar West',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Worli',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Lower Parel',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Mahalaxmi',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Bombay Central',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Mahim-Matunga',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Dockyard',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Sewri-Parel',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Wadala-Sion',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Dadar East',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Chembur',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Ghatkopar',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Powai - Chandivalli',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'JVLR',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Andheri East',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Vile Parle East',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Santacruz East',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Bandra East',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Bandra Entrance',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Bandra Mount Mary',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Bandra Turner Road',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Bandra Rizvi College',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Bandra Linking Road',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Khar West',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Santacruz West',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Juhu',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Andheri Versova',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Andheri West',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Malad West',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Kandivali West',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Goregaon East',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Kandivali East',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Goregaon West',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Borivali East',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Borivali West',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Vile Parle West',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')
Area.create!(:city_id=>'1',:name=>'Kanjurmarg-Vikhroli',:comment=>'This includes the localities of  Kalanagar, Kurla and Bandra Station East which are close to the prominent Bandra Kurla Complex (BKC). BKC is now home to some of India\'s finest corporate houses including ICICI Bank and the National Stock Exchange. The MIG Club (where Sachin Tendulkar grew up) and the MCA Club (where Sachin now practices) are close by. This is an ideal location for people working in the area as well as people looking to be in close proximity to Bandra West - the queen of the Suburbs. The American International School and Arya Vidya Mandir are close by and work well for families with school-going children. The Kalanagar locality in particular is quiet, clean and safe which makes it a slightly nicer locality. The Bandra Station area offers homes at a budget for younger people wanting to party in Bandra West. Kurla on the other side of BKC has the large Kohinoor complex which offers safe community living with modern construction."')

Locality.create!(:name=>'Colaba Causeway',:area_id=>'1')
Locality.create!(:name=>'Cuffe Parade',:area_id=>'1')
Locality.create!(:name=>'World Trade Centre',:area_id=>'1')
Locality.create!(:name=>'Mantralaya',:area_id=>'1')
Locality.create!(:name=>'Opera House',:area_id=>'2')
Locality.create!(:name=>'Charni Road',:area_id=>'2')
Locality.create!(:name=>'Marine Lines',:area_id=>'2')
Locality.create!(:name=>'Nariman Point',:area_id=>'2')
Locality.create!(:name=>'Chowpatty',:area_id=>'2')
Locality.create!(:name=>'Marine Drive',:area_id=>'2')
Locality.create!(:name=>'Kalbadevi',:area_id=>'3')
Locality.create!(:name=>'Ballard Estate',:area_id=>'3')
Locality.create!(:name=>'Crawford Market',:area_id=>'3')
Locality.create!(:name=>'Horniman Circle',:area_id=>'3')
Locality.create!(:name=>'Fountain',:area_id=>'3')
Locality.create!(:name=>'CST',:area_id=>'3')
Locality.create!(:name=>'Altamount Road',:area_id=>'4')
Locality.create!(:name=>'Nepean Sea Road',:area_id=>'4')
Locality.create!(:name=>'Kemps Corner',:area_id=>'4')
Locality.create!(:name=>'Malabar Hill',:area_id=>'4')
Locality.create!(:name=>'Bhuleshwar',:area_id=>'4')
Locality.create!(:name=>'Walkeshwar',:area_id=>'4')
Locality.create!(:name=>'Peddar Road',:area_id=>'4')
Locality.create!(:name=>'Warden Road',:area_id=>'4')
Locality.create!(:name=>'Plaza Cinema',:area_id=>'5')
Locality.create!(:name=>'Shivaji Park',:area_id=>'5')
Locality.create!(:name=>'Portugese Church',:area_id=>'5')
Locality.create!(:name=>'Worli Seaface',:area_id=>'6')
Locality.create!(:name=>'Worli Naka',:area_id=>'6')
Locality.create!(:name=>'Prabhadevi',:area_id=>'6')
Locality.create!(:name=>'Phoenix Mills',:area_id=>'7')
Locality.create!(:name=>'Elphinstone Road',:area_id=>'7')
Locality.create!(:name=>'Saat Raasta',:area_id=>'8')
Locality.create!(:name=>'Arthur Road',:area_id=>'8')
Locality.create!(:name=>'Bycullah',:area_id=>'8')
Locality.create!(:name=>'Mohammed Ali Road',:area_id=>'8')
Locality.create!(:name=>'Tardeo',:area_id=>'9')
Locality.create!(:name=>'Haji Ali',:area_id=>'9')
Locality.create!(:name=>'Grant Road',:area_id=>'9')
Locality.create!(:name=>'Lamington Road',:area_id=>'9')
Locality.create!(:name=>'Mahim',:area_id=>'10')
Locality.create!(:name=>'Cadell Road',:area_id=>'10')
Locality.create!(:name=>'Sheetladevi Temple',:area_id=>'10')
Locality.create!(:name=>'Matunga',:area_id=>'10')
Locality.create!(:name=>'Sandhurst Road',:area_id=>'11')
Locality.create!(:name=>'Cotton Green',:area_id=>'11')
Locality.create!(:name=>'Reay Road',:area_id=>'11')
Locality.create!(:name=>'Mazgaon',:area_id=>'11')
Locality.create!(:name=>'Currey Road',:area_id=>'11')
Locality.create!(:name=>'Sewri',:area_id=>'12')
Locality.create!(:name=>'Parel',:area_id=>'12')
Locality.create!(:name=>'Dosti Acres',:area_id=>'13')
Locality.create!(:name=>'Wadala',:area_id=>'13')
Locality.create!(:name=>'Bhakti Park',:area_id=>'13')
Locality.create!(:name=>'Char Raasta',:area_id=>'13')
Locality.create!(:name=>'Sion',:area_id=>'13')
Locality.create!(:name=>'Chunabhatti',:area_id=>'13')
Locality.create!(:name=>'Hindu Colony',:area_id=>'14')
Locality.create!(:name=>'Kings Circle',:area_id=>'14')
Locality.create!(:name=>'Matunga East',:area_id=>'14')
Locality.create!(:name=>'Five Gardens',:area_id=>'14')
Locality.create!(:name=>'Diamond Garden',:area_id=>'15')
Locality.create!(:name=>'Sindhi Colony',:area_id=>'15')
Locality.create!(:name=>'Deonar',:area_id=>'15')
Locality.create!(:name=>'Union Park',:area_id=>'15')
Locality.create!(:name=>'Golf Club',:area_id=>'15')
Locality.create!(:name=>'Chembur Exchange',:area_id=>'15')
Locality.create!(:name=>'LBS Marg',:area_id=>'16')
Locality.create!(:name=>'Vidya Vihar',:area_id=>'16')
Locality.create!(:name=>'Tilak Nagar',:area_id=>'16')
Locality.create!(:name=>'Kurla Terminus',:area_id=>'16')
Locality.create!(:name=>'Kanjur Marg',:area_id=>'41')
Locality.create!(:name=>'Vikhroli',:area_id=>'41')
Locality.create!(:name=>'Hiranandani Gardens',:area_id=>'17')
Locality.create!(:name=>'Nahar Amrit Shakti',:area_id=>'17')
Locality.create!(:name=>'Raheja Vihar',:area_id=>'17')
Locality.create!(:name=>'Lake Homes',:area_id=>'17')
Locality.create!(:name=>'Saki Vihar Road',:area_id=>'17')
Locality.create!(:name=>'Poonam Nagar',:area_id=>'18')
Locality.create!(:name=>'JVLR Road',:area_id=>'18')
Locality.create!(:name=>'JB Nagar',:area_id=>'19')
Locality.create!(:name=>'Marol-Maroshi',:area_id=>'19')
Locality.create!(:name=>'Saki Naka',:area_id=>'19')
Locality.create!(:name=>'SEEPZ',:area_id=>'19')
Locality.create!(:name=>'Mahakali Caves Road',:area_id=>'19')
Locality.create!(:name=>'Chakala',:area_id=>'19')
Locality.create!(:name=>'Andheri Station East',:area_id=>'19')
Locality.create!(:name=>'Hanuman Road',:area_id=>'20')
Locality.create!(:name=>'Tejpal Scheme',:area_id=>'20')
Locality.create!(:name=>'Parle Exchange',:area_id=>'20')
Locality.create!(:name=>'Nehru Road',:area_id=>'20')
Locality.create!(:name=>'Vakola',:area_id=>'21')
Locality.create!(:name=>'Kalina',:area_id=>'21')
Locality.create!(:name=>'Santacruz Station East',:area_id=>'21')
Locality.create!(:name=>'Sundernagar',:area_id=>'22')
Locality.create!(:name=>'Kalanagar',:area_id=>'22')
Locality.create!(:name=>'BKC',:area_id=>'22')
Locality.create!(:name=>'Kohinoor City',:area_id=>'22')
Locality.create!(:name=>'Kurla',:area_id=>'22')
Locality.create!(:name=>'Bandra Station East',:area_id=>'22')
Locality.create!(:name=>'Reclamation',:area_id=>'23')
Locality.create!(:name=>'Mount Mary Steps',:area_id=>'23')
Locality.create!(:name=>'Hill Road',:area_id=>'23')
Locality.create!(:name=>'Mehboob Studio',:area_id=>'24')
Locality.create!(:name=>'Bandstand',:area_id=>'24')
Locality.create!(:name=>'Mount Mary',:area_id=>'24')
Locality.create!(:name=>'Carter Road',:area_id=>'25')
Locality.create!(:name=>'Turner Road',:area_id=>'25')
Locality.create!(:name=>'Perry Cross Road',:area_id=>'25')
Locality.create!(:name=>'Pali Hill',:area_id=>'25')
Locality.create!(:name=>'Sherly Rajan Road',:area_id=>'26')
Locality.create!(:name=>'Linking Road',:area_id=>'27')
Locality.create!(:name=>'Mini Punjab',:area_id=>'27')
Locality.create!(:name=>'Pali Presidency',:area_id=>'27')
Locality.create!(:name=>'Khar Danda Road',:area_id=>'27')
Locality.create!(:name=>'Khar Station',:area_id=>'28')
Locality.create!(:name=>'Madhu Park',:area_id=>'28')
Locality.create!(:name=>'Khar Subway',:area_id=>'28')
Locality.create!(:name=>'Santacruz Station West',:area_id=>'29')
Locality.create!(:name=>'North Avenue',:area_id=>'29')
Locality.create!(:name=>'Santacruz Garden',:area_id=>'29')
Locality.create!(:name=>'Juhu Tara Road',:area_id=>'30')
Locality.create!(:name=>'Juhu Scheme',:area_id=>'30')
Locality.create!(:name=>'Juhu Post Office',:area_id=>'30')
Locality.create!(:name=>'Gulmohar Road',:area_id=>'30')
Locality.create!(:name=>'NS Road',:area_id=>'30')
Locality.create!(:name=>'DN Nagar',:area_id=>'31')
Locality.create!(:name=>'Versova',:area_id=>'31')
Locality.create!(:name=>'Yari Road',:area_id=>'31')
Locality.create!(:name=>'4 Bungalows',:area_id=>'31')
Locality.create!(:name=>'7 Bungalows',:area_id=>'31')
Locality.create!(:name=>'Lokhandwala',:area_id=>'32')
Locality.create!(:name=>'Oshiwara',:area_id=>'32')
Locality.create!(:name=>'Andheri Station West',:area_id=>'32')
Locality.create!(:name=>'Veera Desai Road',:area_id=>'32')
Locality.create!(:name=>'Versova Exchange',:area_id=>'32')
Locality.create!(:name=>'Shastri Nagar',:area_id=>'32')
Locality.create!(:name=>'Ekta Nagar',:area_id=>'33')
Locality.create!(:name=>'Mindspace',:area_id=>'33')
Locality.create!(:name=>'Patel Nagar',:area_id=>'34')
Locality.create!(:name=>'Gokuldham',:area_id=>'35')
Locality.create!(:name=>'Goregaon Depot',:area_id=>'35')
Locality.create!(:name=>'Royal Palms',:area_id=>'35')
Locality.create!(:name=>'Oberoi Mall',:area_id=>'35')
Locality.create!(:name=>'Thakur Complex',:area_id=>'36')
Locality.create!(:name=>'Kandivalli Station',:area_id=>'36')
Locality.create!(:name=>'Kandivali Lokhandvala',:area_id=>'36')
Locality.create!(:name=>'Mahavir Nagar',:area_id=>'36')
Locality.create!(:name=>'Jawahar Nagar',:area_id=>'37')
Locality.create!(:name=>'Bangur Nagar',:area_id=>'37')
Locality.create!(:name=>'Yogi Nagar',:area_id=>'38')
Locality.create!(:name=>'IC Colony',:area_id=>'39')
Locality.create!(:name=>'Irla',:area_id=>'40')
Locality.create!(:name=>'Lalubhai Park',:area_id=>'40')
Locality.create!(:name=>'Bajaj Road',:area_id=>'40')
Locality.create!(:name=>'Near Vile Parle Station',:area_id=>'40')
Locality.create!(:name=>'SaiBaba Nagar',:area_id=>'39')
Locality.create!(:name=>'Charkop',:area_id=>'36')
Locality.create!(:name=>'Filmcity Road',:area_id=>'35')

BhkConfig.create!(:name => '1 RK')
BhkConfig.create!(:name => '1 BHK')
BhkConfig.create!(:name => '1.5 BHK')
BhkConfig.create!(:name => '2 BHK')
BhkConfig.create!(:name => '2.5 BHK')
BhkConfig.create!(:name => '3 BHK')
BhkConfig.create!(:name => '4 BHK')
BhkConfig.create!(:name => '5 BHK')
BhkConfig.create!(:name => 'Villa')
BhkConfig.create!(:name => 'PG')

PoiType.create!(:name => 'Building')
PoiType.create!(:name => 'Temple')
PoiType.create!(:name => 'Church')
PoiType.create!(:name => 'Mosque')
PoiType.create!(:name => 'Gurudwara')
PoiType.create!(:name => 'Main Road')
PoiType.create!(:name => 'Intersection')
PoiType.create!(:name => 'Railway Station')
PoiType.create!(:name => 'Bus Depot')
PoiType.create!(:name => 'Airport')
PoiType.create!(:name => 'Shopping Mall')
PoiType.create!(:name => 'Cinema Theatre')
PoiType.create!(:name => 'School')
PoiType.create!(:name => 'Hospital')
PoiType.create!(:name => 'Garden')
PoiType.create!(:name => 'Museum')
PoiType.create!(:name => 'Market')

Facility.create!(:name => 'Clubhouse', :is_building => true)
FacilityFeature.create!(:name => 'Tennis', :facility_id => 1)
FacilityFeature.create!(:name => 'Badminton', :facility_id => 1)
FacilityFeature.create!(:name => 'Table Tennis', :facility_id => 1)
FacilityFeature.create!(:name => 'Billiards', :facility_id => 1)
FacilityFeature.create!(:name => 'Squash', :facility_id => 1)
FacilityFeature.create!(:name => 'Basketball', :facility_id => 1)
FacilityFeature.create!(:name => 'Carrom', :facility_id => 1)
FacilityFeature.create!(:name => 'Card Tables', :facility_id => 1)
FacilityFeature.create!(:name => 'Banquet Hall', :facility_id => 1)
FacilityFeature.create!(:name => 'Auditorium', :facility_id => 1)
FacilityFeature.create!(:name => 'Bar', :facility_id => 1)
FacilityFeature.create!(:name => 'Snacks', :facility_id => 1)
FacilityFeature.create!(:name => 'Video games', :facility_id => 1)

Facility.create!(:name => 'Gym', :is_building => true)
FacilityFeature.create!(:name => 'Treadmills', :facility_id => 2)
FacilityFeature.create!(:name => 'Weights', :facility_id => 2)
FacilityFeature.create!(:name => 'Biking machines', :facility_id => 2)
FacilityFeature.create!(:name => 'Professional Trainers', :facility_id => 2)
FacilityFeature.create!(:name => 'Weight machines', :facility_id => 2)
FacilityFeature.create!(:name => 'Rowing machines', :facility_id => 2)

Facility.create!(:name => 'Swimming Pool', :is_building => true)
FacilityFeature.create!(:name => 'Regular pool', :facility_id => 3)
FacilityFeature.create!(:name => 'Kiddie pool', :facility_id => 3)
FacilityFeature.create!(:name => 'Olympic size pool', :facility_id => 3)
FacilityFeature.create!(:name => 'Diving boards', :facility_id => 3)
FacilityFeature.create!(:name => 'Lap pool', :facility_id => 3)
FacilityFeature.create!(:name => 'Jacuzzi', :facility_id => 3)

Facility.create!(:name => 'Visitor Parking', :is_building => true)
FacilityFeature.create!(:name => 'Plenty of visitor parking', :facility_id => 4)
FacilityFeature.create!(:name => 'Limited Visitor parking', :facility_id => 4)

Facility.create!(:name => 'Childrens Play Area', :is_building => true)
FacilityFeature.create!(:name => 'Slides', :facility_id => 5)
FacilityFeature.create!(:name => 'Swings', :facility_id => 5)
FacilityFeature.create!(:name => 'Seesaws', :facility_id => 5)
FacilityFeature.create!(:name => 'Sandpit', :facility_id => 5)
FacilityFeature.create!(:name => 'Climbing Cage', :facility_id => 5)
FacilityFeature.create!(:name => 'Rides', :facility_id => 5)

Facility.create!(:name => 'Gated Community', :is_building => true)
FacilityFeature.create!(:name => 'Walking track', :facility_id => 6)
FacilityFeature.create!(:name => 'Lawns', :facility_id => 6)
FacilityFeature.create!(:name => 'Garden', :facility_id => 6)

Facility.create!(:name => 'Security', :is_building => true)
FacilityFeature.create!(:name => 'Intercom', :facility_id => 7)
FacilityFeature.create!(:name => 'At building entrance', :facility_id => 7)
FacilityFeature.create!(:name => 'At Community entrance', :facility_id => 7)

Facility.create!(:name => 'Lifts', :is_building => true)
FacilityFeature.create!(:name => 'Basic lifts', :facility_id => 8)
FacilityFeature.create!(:name => 'Modern lifts', :facility_id => 8)
FacilityFeature.create!(:name => 'Service lifts', :facility_id => 8)

Restriction.create!(:name => 'No Single Men')
Restriction.create!(:name => 'No Single Women')
Restriction.create!(:name => 'No Non-vegetarian')
Restriction.create!(:name => 'No Corporate Lease')
Restriction.create!(:name => 'No Individual Lease')
Restriction.create!(:name => 'No Guest house')
Restriction.create!(:name => 'No Pets')

Service.create!(:name => 'Restaurant')
Service.create!(:name => 'Electrician')
Service.create!(:name => 'Plumber')
Service.create!(:name => 'Grocery Store')
Service.create!(:name => 'Maid Service')

ParkingType.create!(:name => 'Covered Parking')
ParkingType.create!(:name => 'Open Parking')

BathroomType.create!(:name => 'Indian Toilet')
BathroomType.create!(:name => 'Western Toilet')
BathroomType.create!(:name => 'Integrated Bathroom and Toilet')

Direction.create!(:name => 'North')
Direction.create!(:name => 'North-East')
Direction.create!(:name => 'East')
Direction.create!(:name => 'South-East')
Direction.create!(:name => 'South')
Direction.create!(:name => 'South-West')
Direction.create!(:name => 'West')
Direction.create!(:name => 'North-West')

BalconyType.create!(:name => 'Balcony')
BalconyType.create!(:name => 'Sit-out')
BalconyType.create!(:name => 'Terrace')

Facility.create!(:name => 'Furniture', :is_building => false)
FacilityFeature.create!(:name => 'Dining table', :facility_id => 9)
FacilityFeature.create!(:name => 'Dining chairs', :facility_id => 9)
FacilityFeature.create!(:name => 'Sofa', :facility_id => 9)
FacilityFeature.create!(:name => 'Chairs', :facility_id => 9)
FacilityFeature.create!(:name => 'Beds', :facility_id => 9)
FacilityFeature.create!(:name => 'TV Cabinets', :facility_id => 9)

Facility.create!(:name => 'White Goods', :is_building => false)
FacilityFeature.create!(:name => 'TV', :facility_id => 10)
FacilityFeature.create!(:name => 'Fridge', :facility_id => 10)
FacilityFeature.create!(:name => 'Microwave', :facility_id => 10)
FacilityFeature.create!(:name => 'Water purifier', :facility_id => 10)
FacilityFeature.create!(:name => 'Fans', :facility_id => 10)
FacilityFeature.create!(:name => 'Washing machine', :facility_id => 10)

Facility.create!(:name => 'Kitchen', :is_building => false)
FacilityFeature.create!(:name => 'Modular kitchen', :facility_id => 11)
FacilityFeature.create!(:name => 'Cylinders provided', :facility_id => 11)
FacilityFeature.create!(:name => 'Electric Gas', :facility_id => 11)
FacilityFeature.create!(:name => 'Electric Chimney', :facility_id => 11)

Facility.create!(:name => 'Wardrobes', :is_building => false)
FacilityFeature.create!(:name => 'Integrated wardrobes', :facility_id => 12)
FacilityFeature.create!(:name => 'Wardrobes provided', :facility_id => 12)

Facility.create!(:name => 'Layout', :is_building => false)
FacilityFeature.create!(:name => 'French windows', :facility_id => 13)
FacilityFeature.create!(:name => 'Dry Area', :facility_id => 13)
FacilityFeature.create!(:name => 'Water storage loft', :facility_id => 13)

Facility.create!(:name => 'Utilities', :is_building => false)
FacilityFeature.create!(:name => 'Piped Gas', :facility_id => 14)
FacilityFeature.create!(:name => 'Landline available', :facility_id => 14)
FacilityFeature.create!(:name => 'Internet available', :facility_id => 14)
FacilityFeature.create!(:name => 'DTH', :facility_id => 14)
FacilityFeature.create!(:name => 'Cable', :facility_id => 14)

Facility.create!(:name => 'Air Conditioners', :is_building => false)
FacilityFeature.create!(:name => 'Window Acs', :facility_id => 15)
FacilityFeature.create!(:name => 'Split Acs', :facility_id => 15)

Facility.create!(:name => 'Servant Quarters', :is_building => false)
Facility.create!(:name => 'Parking', :is_building => false)
Facility.create!(:name => 'Balconies', :is_building => false)

Labelling.create!(:name => 'Reference', :is_flat_contact_label => true)
Labelling.create!(:name => 'Tenant', :is_flat_contact_label => true)
Labelling.create!(:name => 'Landlord', :is_flat_contact_label => true)
Labelling.create!(:name => 'Cleaning Client', :is_flat_contact_label => true)
Labelling.create!(:name => 'Broker', :is_flat_contact_label => true)

Labelling.create!(:name => 'Ignore', :is_flat_contact_label => false)
Labelling.create!(:name => 'Priority', :is_flat_contact_label => false)
Labelling.create!(:name => 'Important', :is_flat_contact_label => false)
Labelling.create!(:name => 'Regular', :is_flat_contact_label => false)
Labelling.create!(:name => 'Revisit', :is_flat_contact_label => false)
Labelling.create!(:name => 'Demanding', :is_flat_contact_label => false)

Flatype.create!(:name => 'Direct')
Flatype.create!(:name => 'Partner')
Flatype.create!(:name => 'Broker')
Flatype.create!(:name => 'TBO')

Furnstat.create!(:name => "Furnished")
Furnstat.create!(:name => "Semi-Furnished")
Furnstat.create!(:name => "Unfurnished")
Furnstat.create!(:name => "Bare")

InteractionType.create(:name=>"Note")
InteractionType.create(:name=>"Meet")
InteractionType.create(:name=>"Email")
InteractionType.create(:name=>"Call")
InteractionType.create(:name=>"Showing")

RentYear.create!(:name => "2012")
RentYear.create!(:name => "2013")
RentYear.create!(:name => "2014")
RentYear.create!(:name => "2015")
RentYear.create!(:name => "2016")

# These are testing seeds

User.create!(:name => "Kenneth Serrao", :email => 'kenneth@bpe.com', :password => 'secret', :password_confirmation => 'secret', :admin => false)
User.create!(:name => "Kaushal Shah", :email => 'kaushal@bpe.com', :password => 'secret', :password_confirmation => 'secret', :admin => false)
User.create!(:name => "Arijit Lahiri", :email => 'arijit@ptotem.com', :password => 'secret', :password_confirmation => 'secret', :admin => false)
User.create!(:name => "Deepak Jhavar", :email => 'deepak@bpe.com', :password => 'secret', :password_confirmation => 'secret', :admin => false)

DealStage.create!(:name => "Closed")
DealStage.create!(:name => "Token Given")
DealStage.create!(:name => "Registered")
DealStage.create!(:name => "Payments Completed")
DealStage.create!(:name => "Move In")
DealStage.create!(:name => "Processed")

DealRelation.create!(:name=>"Broker")
DealRelation.create!(:name=>"Landlord")
DealRelation.create!(:name=>"Tenant")
DealRelation.create!(:name=>"Employee")

